# _config.yml

url: "https://bleckert.se" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Segling@bleckert.se" # the name of your site, e.g. ACME Corp.

exclude: []

#posts
permalink: /blog/:title

#pagnation plugin
paginate: 5

plugins:
  - jekyll-postcss
  - jekyll-paginate